config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :menus
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_one_attached :desert
  has_one_attached :breakfast
  has_one_attached :cena
  has_one_attached :comida
  has_one_attached :bebida
  has_one_attached :llevar
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attr_accessor :current_password

  validates :name, presence: true
  validates :username, format: { with: /\A[\w-]+\z/, message: "doesn't meet format requirements" }
  validates :username, uniqueness: true, presence: true

  def current_password_is_correct
    # Check if the user tried changing his/her password
    if !password.blank?
      # Get a reference to the user since the "authenticate" method always returns false when calling on itself.
      user = User.find_by_id(id)

      # Check if the user CANNOT be authenticated with the entered current password
      if user.authenticate(current_password) == false
        # Add an error stating that the current password is incorrect
        errors.add(:current_password, 'is incorrect.')
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?
  helper_method :logged_in_user

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logged_in_user
    unless logged_in?
      redirect_to root_path
      flash[:danger] = "Please log in or create a new user."
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :update, :create, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to root_path, notice: 'Menu was successfully created.' }
        format.json { render root_path, status: :created, location: @menu }
      else
        format.html { render 'users#show' }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to root_path, notice: 'Menu was successfully updated.' }
        format.json { render root_path, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_params
      params.require(:menu).permit(:desert, :breakfast, :comida, :llevar, :cena, :bebida)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: 'Logged In'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged Out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit, :update, :show, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @menus = Menu.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @menus = Menu.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render root_path, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :username, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantMenuTemp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :desert %>
    <%= form.file_field :desert %>
  </div>

  <div class="field">
    <%= form.label :breakfast %>
    <%= form.file_field :breakfast %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menus</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', root_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/users/_form.html.erb
<%= stylesheet_link_tag 'users', media: 'all' %>

<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <ul class="text-center d-flex flex-column p-0">
      <% user.errors.full_messages.each do |message| %>
        <li class="list-item text-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3 class="form-title text-light mb-1 mt-1 mb-lg-4 mt-lg-3">Register</h3>

  <div class="field text-light">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field text-light">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field text-light">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field text-light">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit 'Sign Up', class:'button text-uppercase'%>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= stylesheet_link_tag 'users', media: 'all' %>

<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <ul class="text-center d-flex flex-column p-0">
      <% user.errors.full_messages.each do |message| %>
        <li class="list-item text-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3 class="form-title text-light mb-1 mt-1 mb-lg-4 mt-lg-3"></h3>

  <div class="field text-light">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field text-light">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field text-light">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field text-light">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field text-light">
    <%= form.label :current_password %>
    <%= form.password_field :current_password, hint: "we need your current password to confirm your changes", required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
  </div>

  <div class="actions">
    <%= form.submit 'Confirm', class:'button text-uppercase'%>
  </div>
<% end %>

app/views/users/edit.html.erb
<nav class="container-fluid mt-3">
  <div class="row">
    <div class="col-6 text-center text-upperase text-info">
      <%= link_to 'Logout', logout_path, method: :delete, class:"text-uppercase text-info" %>
    </div>
    <div class="col-6 text-center text-upperase text-info">
      <%= link_to 'Back', user_path(@user), class: 'text-uppercase text-info' %>
    </div>
  </div>
</nav>

<div class="container-fluid d-flex justify-content-center mt-lg-5 mt-1">
  <h1 aria-label="A pen by Michiel Bijl" data-label="User">
    <span aria-label="Ed"></span>
    <span aria-label="it"></span>
  </h1>
</div>

<%= render 'form_edit', user: @user %>

<div class="container-fluid text-center mt-4 mb-2">
  <%= link_to 'Delete User', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-uppercase text-danger' %>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'index', media: 'all' %>
<style>
@import url('https://fonts.googleapis.com/css2?family=Cookie&display=swap');
</style> 
<p id="notice" class="text-uppercase text-success text-center bg-grey"><%= notice %></p>

<header class="header-container container-fluid bg-light d-flex justify-content-center">
  <div class="logo-container">
    <%= link_to image_tag("https://logoipsum.com/logo/logo-5.svg"), login_path, class:"logotipo"%>
  </div>
</header>

<div id="main-banner">
  <img src="https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" alt="Welcome to Resto">
  <div class="banner-text-cont">
    <h1>Restaurant Menu</h1>
    <p class="text-light">Los mejores platillos, para los mejores paladares</p> 
  </div>
</div>
        
<div class="wrapper">
  <section id="home-menu">
    <h2>Menu</h2>
  </section>
</div>

<%# Aquí empieza la galería de menú %>
<% @menus.each do |p|%>

<div class="wrapper1">

<% if p.desert.attached? || p.breakfast.attached? %>
  <h1 class="contenth1">Desayunos y Postres</h1>
<h2 class="contenth2">Comienza el día con el mejor ánimo.</h2>
<% end %>

<div class="blocks">

<% if p.desert.attached? %>
  <div class="block">
    <img src="<%=(url_for(p.desert))%>" class="image">
    <% if false %>
    <div class="info">
      <div class="title">Lorem ipsum dolor.</div>
      <div class="date">APRIL 3, 2015</div>
    </div>
    <% end %>
  </div>
<%end%>

<% if p.breakfast.attached? %>
  <div class="block">
    <img src="<%=(url_for(p.breakfast))%>" class="image">
    <% if false %>
    <div class="info">
      <div class="title">Lorem ipsum dolor sit.</div>
      <div class="date">MARCH 7, 2015</div>
    </div>
    <% end %>
  </div>
<%end%>
</div>
</div>


<div class="wrapper1">

<% if p.llevar.attached? || p.comida.attached? %>
  <h1 class="contenth1">Para llevar y Comida</h1>
<h2 class="contenth2">Comienza el día con el mejor ánimo.</h2>
<% end %>

<div class="blocks">
<% if p.comida.attached? %>
  <div class="block">
    <img src="<%=(url_for(p.comida))%>" class="image">
    <% if false %>
    <div class="info">
      <div class="title">Lorem ipsum dolor.</div>
      <div class="date">APRIL 3, 2015</div>
    </div>
    <% end %>
  </div>
<%end%>

<% if p.llevar.attached? %>
  <div class="block">
    <img src="<%=(url_for(p.llevar))%>" class="image">
    <% if false %>
    <div class="info">
      <div class="title">Lorem ipsum dolor sit.</div>
      <div class="date">MARCH 7, 2015</div>
    </div>
    <% end %>
  </div>
<%end%>
</div>
</div>

<div class="wrapper1">

<% if p.bebida.attached? || p.cena.attached? %>
  <h1 class="contenth1">Cena y Bebida</h1>
<h2 class="contenth2">Comienza el día con el mejor ánimo.</h2>
<% end %>

<div class="blocks">

<% if p.bebida.attached? %>
  <div class="block">
    <img src="<%=(url_for(p.bebida))%>" class="image">
    <% if false %>
    <div class="info">
      <div class="title">Lorem ipsum dolor.</div>
      <div class="date">APRIL 3, 2015</div>
    </div>
    <% end %>
  </div>
<%end%>

<% if p.cena.attached? %>  
  <div class="block">
    <img src="<%=(url_for(p.cena))%>" class="image">
    <% if false %>
    <div class="info">
      <div class="title">Lorem ipsum dolor sit.</div>
      <div class="date">MARCH 7, 2015</div>
    </div>
    <% end %>
  </div>
</div>
</div>
<% end %>
<% end%>
<br>

app/views/users/new.html.erb
<nav class="container-fluid mt-3">
  <div class="row">
    <div class="col-6 text-center text-upperase text-info">
      <%= link_to 'Home', root_path, class: 'text-uppercase text-info' %>
    </div>
    <div class="col-6 text-center text-upperase text-info">
      <%= link_to 'Log In', login_path, class:"text-uppercase text-info" %>
    </div>
  </div>
</nav>

<div class="container-fluid d-flex justify-content-center mt-lg-5 mt-1">
  <h1 aria-label="A pen by Michiel Bijl" data-label="Sign Up">
    <span aria-label="Me"></span>
    <span aria-label="nu"></span>
  </h1>
</div>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice" class="text-uppercase text-success text-center bg-grey"><%= notice %></p>

<style>
@import url('https://fonts.googleapis.com/css2?family=Cookie&display=swap');
</style> 

<nav class="container-fluid d-md-none">
  <div class="row">
    <div class="col-6 text-center text-upperase text-info">
      <%= link_to 'Logout', logout_path, method: :delete, class:"text-uppercase text-info" %>
    </div>
    <div class="col-6 text-center text-upperase text-info">
      <%= link_to 'Edit user', edit_user_path(@user), class:"text-uppercase text-info" %>
    </div>
  </div>
</nav>

<div class="container-fluid jumbo-pack d-flex justify-content-center mt-3 mb-3">
    <div class="jumbotronh0 d-none d-md-block">
      <%= link_to 'Logout', logout_path, method: :delete, class:"link-user" %>
    </div>
    <div class="jumbotronh11">
      <h1 class="jumbotronh1" aria-label="A pen by Michiel Bijl" data-label="Dear User">
        <span aria-label="Wel"></span>
        <span aria-label="come"></span>
      </h1>
    </div>
    <div class="jumbotronh2 d-none d-md-block">
      <%= link_to 'Edit user', edit_user_path(@user), class:"link-user1" %>
    </div>
</div>

<div class="menu-show container-fluid d-flex flex-column align-items-center justify-content-center text-center">
  <div class="username-container d-flex align-items-center">
    <h3 class="mt-2 mb-2 text-light"><%= @user.name %></h3>
  </div>
  <% @menus.each do |menu|%>
    <%= form_for menu do |f| %>
      <% if menu.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>
  
          <ul>
          <% menu.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
  
        <div class="container-fluid d-flex flex-column align-items-center flex-lg-row mb-3">
          <div class="form-container">
            <div class="">
            <% if menu.desert.attached? %>
              <h5 class="menu-class">Postres</h5>
              <img src="<%=(url_for(menu.desert))%>" class="image-menu">
            <% end %>
            </div>
          </div>
          <div class="form-container-file">
            <div class="field mx-auto">
              <%= f.label :desert, class:'text-light text-uppercase' %><br>
              <%= f.file_field :desert, class:'button text-uppercase' %>
            </div>
          </div>
        </div>
  
        <div class="container-fluid d-flex flex-column align-items-center flex-lg-row mb-3">
          <div class="form-container">
            <div class="">
            <% if menu.breakfast.attached? %>
              <h5 class="menu-class">Breakfast</h5>
              <img src="<%=(url_for(menu.breakfast))%>" class="image-menu">
            <% end %>
            </div>
          </div>
          <div class="form-container-file">
            <div class="field mx-auto">
              <%= f.label :breakfast, class:'text-light text-uppercase' %><br>
              <%= f.file_field :breakfast, class:'button text-uppercase' %>
            </div>
          </div>
        </div>

        <div class="container-fluid d-flex flex-column align-items-center flex-lg-row mb-3">
          <div class="form-container">
            <div class="">
            <% if menu.comida.attached? %>
              <h5 class="menu-class">Comida</h5>
              <img src="<%=(url_for(menu.comida))%>" class="image-menu">
            <% end %>
            </div>
          </div>
          <div class="form-container-file">
            <div class="field mx-auto">
              <%= f.label :comida, class:'text-light text-uppercase' %><br>
              <%= f.file_field :comida, class:'button text-uppercase' %>
            </div>
          </div>
        </div>

        <div class="container-fluid d-flex flex-column align-items-center flex-lg-row mb-3">
          <div class="form-container">
            <div class="">
            <% if menu.bebida.attached? %>
              <h5 class="menu-class">Bebida</h5>
              <img src="<%=(url_for(menu.bebida))%>" class="image-menu">
            <% end %>
            </div>
          </div>
          <div class="form-container-file">
            <div class="field mx-auto">
              <%= f.label :bebida, class:'text-light text-uppercase' %><br>
              <%= f.file_field :bebida, class:'button text-uppercase' %>
            </div>
          </div>
        </div>

        <div class="container-fluid d-flex flex-column align-items-center flex-lg-row mb-3">
          <div class="form-container">
            <div class="">
            <% if menu.llevar.attached? %>
              <h5 class="menu-class">Comida para llevar</h5>
              <img src="<%=(url_for(menu.llevar))%>" class="image-menu">
            <% end %>
            </div>
          </div>
          <div class="form-container-file">
            <div class="field mx-auto">
              <%= f.label :llevar, class:'text-light text-uppercase' %><br>
              <%= f.file_field :llevar, class:'button text-uppercase' %>
            </div>
          </div>
        </div>

        <div class="container-fluid d-flex flex-column align-items-center flex-lg-row mb-3">
          <div class="form-container">
            <div class="">
            <% if menu.cena.attached? %>
              <h5 class="menu-class">Cena</h5>
              <img src="<%=(url_for(menu.cena))%>" class="image-menu">
            <% end %>
            </div>
          </div>
          <div class="form-container-file">
            <div class="field mx-auto">
              <%= f.label :cena, class:'text-light text-uppercase' %><br>
              <%= f.file_field :cena, class:'button text-uppercase' %>
            </div>
          </div>
        </div>
  
      <div class="actions">
        <%= f.submit 'Aceptar cambios', class:'button-final text-uppercase' %>
      </div>
    <% end %>
  <% end %>
</div>